.TH qmail-autoresponder 1
.SH NAME
qmail-autoresponder \- Produce automatic responses with qmail
.SH SYNOPSIS
.B qmail-autoresponder
[
.B \-cLNqT
] [
.B -H STR
] [
.B -h STR
] [
.B -n NUM
] [
.B -s STR
] [
.B -t TIME
] [
.B MESSAGE-FILE
]
.I DIRECTORY
.SH DESCRIPTION
.B qmail-autoresponder
sends an automatically-generated message in response to an incoming
message.  By default, it limits the number of responses it sends to a
maximum of one message per hour per sender.  It will not respond to
any known mailing list, nor will it respond to either bounces or
loops.
.P
The
.B MESSAGE-FILE
is used as the response message, and must contain a complete mail
message including
.I From:
and
.I Subject:
headers.
If the
.B MESSAGE-FILE
argument is not present, it defaults to
.IR message.txt .
All occurrences of
.I %S
in the message file are replaced with the original message's subject.
To put a percent sign in the message, write it as
.IR %% .
.P
.B qmail-autoresponder
limits the rate at which it sends responses to each recipient to
prevent mail flooding or denial-of-service attacks.
For each response it sends, it creates a file in
.BR DIRECTORY .
The name of that file consists of the process ID of
.BR qmail-autoresponder ,
a period, the current UNIX time number, and the envelope sender
address (with any
.I /
characters replaced with
.I :
to prevent creation of files outside of
.BR DIRECTORY ).
When it receives a message, it scans
.BR DIRECTORY .
Any files that are older than the time interval (see below) are
deleted and ignored.  If the number of remaining files with the same
sender address is greater than or equal to the maximum number of
replies, no response is generated.
.SH OPTIONS
.TP
.B -c
Copy the message into the response.
.TP
.B -H STR
If this option is given and
.B -h
is not, the headers listed in
.B STR
are omitted when copying from the message into the response.  Separate
header names with a colon.
.TP
.B -h STR
If this option is given, only the headers listed in
.B STR
are copied from the message into the response.  Separate header names
with a colon.  If neither this nor
.B -H
are used, all headers are copied.
.TP
.B -L
Create new files (instead of making links) for each recipient file.
This uses more inodes, but may be required for filesystems (such as
Coda) that don't handle links properly.
.TP
.B -N
Write the generated response to standard output instead of sending it.
.TP
.B -n NUM
Set the maximum number of replies per
.B TIME
(defaults to 1).
.TP
.B -q
Quiet.  Don't show error messages.
.TP
.B -s STR
Add a subject line to the response message composed of the prefix
.I STR
followed by the original subject.  This can also be accomplished by
putting the following line at the start of the message file:

.EX
Subject: STR %S
.EE

.TP
.B -T
Do not add a
.I To: <SENDER>
line to the response.
.TP
.B -t TIME
Set the interval during which responses are counted (in seconds)
(defaults to 1 hour).
.SH RETURN VALUE
Exits zero if there were no problems, otherwise exits 111.
.SH ENVIRONMENT
.TP
.B DTLINE
.B qmail-autoresponder
searches for this line (generated by qmail-local) in the input and
bounces the message if it is present (which indicates a mail loop).
It then adds the line to the output.
.TP
.B SENDER
This contains the envelope sender address and is used as the address
to send the reply to.
