.\" $Id$
.TH qmail-autoresponder 1
.SH NAME
qmail-autoresponder \- Produce automatic responses with qmail
.SH SYNOPSIS
.B qmail-autoresponder
[
.B \-cLNqT
] [
.BR "-O NAME" [ =VALUE ]
] [
.B -n NUM
] [
.B -s STR
] [
.B -t TIME
] [
.I MESSAGE-FILE
]
.I DIRECTORY
.SH DESCRIPTION
.B qmail-autoresponder
sends an automatically-generated message in response to an incoming
message.
It also tracks the number of responses it sends to each sender in
order to limit the rate at which it sends responses, to prevent mail
flooding or denial of service attacks.
By default, it limits the number of responses it sends to a
maximum of one message per hour per sender.  It will not respond to
any known mailing list, nor will it respond to either bounces or
loops.
.P
The
.I MESSAGE-FILE
is used as the response message, and must contain a complete mail
message including
.I From:
and
.I Subject:
headers.
If the
.I MESSAGE-FILE
argument is not present, it defaults to
.IR message.txt .
All occurrences of
.I %S
in the message file are replaced with the original message's subject,
.I %s
with the original message's sender (to which the response will be sent), and
.I %r
with the original message's recipient.
To put a percent sign in the message, write it as
.IR %% .
.SS RESPONSE COUNTING
For each response
.B qmail-autoresponder
sends, it creates a file in
.IR DIRECTORY .
The name of that file consists of the current UNIX time number, a period,
the process ID of
.BR qmail-autoresponder ,
a period, and the envelope sender address (with any
.I /
characters replaced with
.I :
to prevent creation of files outside of
.IR DIRECTORY ).
When it receives a message, it scans
.IR DIRECTORY .
Any files that are older than the time interval (see below) are
deleted and ignored.  If the number of remaining files with the same
sender address is greater than or equal to the maximum number of
replies, no response is generated.
.SS LOGGING
If
.I DIRECTORY
contains a writeable file named
.IR log.txt ,
then a line is added to this file each time a sender is processed.  The
format of these lines are as follows:
.RS
.EX
TIMESTAMP +SENDER
TIMESTAMP -SENDER
.EE
.RE
The first line indicates a message was sent to the sender, and the
second that a message was not sent.  The timestamp is expressed as
standard UNIX time (the number of seconds since Jan 1 1970 GMT).
.SH OPTIONS
.B qmail-autoresponder
supports options specified on the command line, in a file named
.BR config.txt ,
and as individual files in
.IR DIRECTORY .
If
.B config.txt
is present, any individual config files are ignored.
Option files in the directory (either
.B config.txt
or individual files) override options set on the command line.
.P
The
.B config.txt
file contains one setting per line, with the option name separated from the value by a
.IR = .
Spaces around the
.I =
are stripped.
The value extends from the first non-space character to the end of the line.
Lines starting with
.I #
are ignored.
.P
The message may also be placed in this configuration file. It is
separated from the settings by a single blank line. If present,
.B message.txt
is not read for the response message.
.P
For example:
.RS
.EX
copymsg=1
# Keep all the X-* headers along with the subject.
headerkeep = subject:x-*
bcc = sendmeacopy@example.com
starttime = 2018-03-14 15:59:00
subject=This is a very long response subject that does not include the original

From: Automatic Responder <recipient@example.com>
Subject: Vacation response (%S)

This is an automated response to your email...
.EE
.RE
.SS "COMMAND LINE"
.TP
.B -c
Equivalent to
.B -O copymsg=1
.TP
.B -L
Create new files (instead of making links) for each recipient file.
This uses more inodes, but may be required for filesystems (such as
Coda) that don't handle links properly.
.TP
.B -N
Write the generated response to standard output instead of sending it.
.TP
.B -n NUM
Equivalent to
.B -O msglimit=NUM
.TP
.BR "-O NAME" [ =VALUE ]
Sets named option
.B NAME
to
.BR VALUE .
If
.B VALUE is omitted, a value of
.B 1
is used.  See below for all the named options.
.TP
.B -q
Quiet.  Don't show error messages.
.TP
.B -s STR
Equivalent to
.B -O subject_prefix=STR
.TP
.B -T
Do not add a
.I To: <SENDER>
line to the response.
.TP
.B -t TIME
Equivalent to
.B -O timelimit=TIME
.SS "NAMED OPTIONS"
.TP
.B bcc \fR(string)
If given, all responses are copied to this address in addition to the
original sender.
.TP
.B copymsg \fR(boolean)
Copy the original message into the response.
.TP
.B endtime \fR(string)
Set the ending time for which this autoresponder is active.
Messages received after this time will not cause a response to be generated.
.TP
.B headerkeep \fR(string)
If this option is given, only the headers listed in the value are copied
from the message into the response.  Separate header names with a colon.
If neither this nor
.B headerstrip
are used, all headers are copied.
.TP
.B headerstrip \fR(string)
If this option is given and
.B headerkeep
is not, the headers listed in the value are omitted when copying from
the message into the response.  Separate header names with a colon.
Header names are treated as patterns, and so may contain
.I *
to match any string.  For example, the pattern
.I x-*
will match the headers
.I X-DomainKeys:
and
.IR X-SpamLevel: .
.TP
.B msglimit \fR(integer)
Set the maximum number of replies per
.B timelimit
(defaults to 1).
.TP
.B no_inreplyto \fR(boolean)
Do not add an
.I In-Reply-To:
header to the outgoing message.  Normally, if a
.I Message-Id:
header is found in the original message,
.B qmail-autoresponder
will add the contents of that header to the outgoing message.  This
allows some email programs to group responses more intelligently.
.TP
.B numlines \fR(integer)
Limits the maximum number of lines copied from the original message body
into the response.  This option is only relevant if the
.B copymsg
option is also used.  If not given, all the lines in the original
message body are copied.  This limit does not impact how many lines of
the header are copied.
.TP
.B separator \fR(string)
Add a separator line (or lines) between the response message and the
copied message.
.TP
.B starttime \fR(string)
Set the starting time for which this autoresponder is active.
Messages received before this time will not cause a response to be generated.
.TP
.B subject_prefix \fR(string)
Add a subject line to the response message composed of the prefix
.I STR
followed by the original subject.  This can also be accomplished by
putting the following line at the start of the message file:

.EX
Subject: STR %S
.EE
.TP
.B timelimit \fR(integer)
Set the interval during which responses are counted (in seconds)
(defaults to 1 hour).
.SH RETURN VALUE
Exits zero if there were no problems, otherwise exits 111.
.SH ENVIRONMENT
.TP
.B DTLINE
.B qmail-autoresponder
searches for this line (generated by qmail-local) in the input and
bounces the message if it is present (which indicates a mail loop).
It then adds the line to the output.
.TP
.B SENDER
This contains the envelope sender address and is used as the address
to send the reply to.
