.\" $Id$
.TH qmail-autoresponder-mysql 1
.SH NAME
qmail-autoresponder-mysql \- Produce automatic responses with qmail
.SH SYNOPSIS
.B qmail-autoresponder-mysql
[
.B \-cLNqT
] [
.BR "-O NAME" [ =VALUE ]
] [
.B -n NUM
] [
.B -s STR
] [
.B -t TIME
]
.I USERNAME DOMAIN
[
.I TABLE_PREFIX
]
.SH DESCRIPTION
.B qmail-autoresponder-mysql
sends an automatically-generated message in response to an incoming
message.  By default, it limits the number of responses it sends to a
maximum of one message per hour per sender.  It will not respond to
any known mailing list, nor will it respond to either bounces or
loops.
.P
The
.I USERNAME
and
.I DOMAIN
arguments are used to select which autoresponder to use from the MySQL
database.  If a record in the
.B autoresponder
table matches the username and domain, the program purges old records
for that autoresponder from the
.B response
table and then counts the remaining responses listed there.  If a
response is sent, a record is also added to that table.
.P
If a
.I TABLE_PREFIX
argument is given, all table names are prefixed with that string.  For
example, if
.I TABLE_PREFIX
is
.B q_
then the tables used are
.B q_autoresponder
and
.BR q_response .
This can be used to allow these tables to co-exist with tables for other
programs in the same database.
.P
See the man page for
.BR qmail-autoresponder (1)
for more details on options and general autoresponder behavior.
.SH OPTIONS
.B qmail-autoresponder-mysql
supports options specified on the command line and as fields in the
.B autoresponder
table.  Option fields are named
.B opt_\fIOPTION
in the database, and override options set on the command line.  See the
man page for
.BR qmail-autoresponder (1)
for a full list of options.
.SH EXAMPLES
Typical usage in a
.B .qmail-default
file would be as follows:

.EX
|qmail-autoresponder-mysql -- "$EXT" "$HOST"
.EE
.SH ENVIRONMENT
.TP
.B DTLINE
.B qmail-autoresponder-mysql
searches for this line (generated by qmail-local) in the input and
bounces the message if it is present (which indicates a mail loop).
It then adds the line to the output.
.TP
.B MYSQL_DB
.TP
.B MYSQL_HOST
.TP
.B MYSQL_PASS
.TP
.B MYSQL_SOCKET
.TP
.B MYSQL_USER
These set the default parameters for the MySQL database connection.  If
not set,
.B qmail-autoresponder-mysql
uses the defaults in the
.B qmail-autoresponder
group in the MySQL option file.
.TP
.B SENDER
This contains the envelope sender address and is used as the address
to send the reply to.
.SH "SEE ALSO"
qmail-autoresonder(1)
